# .copilot/commands/paper/requirements.yaml
name: "paper.requirements"
display-name: "Set technical requirements"
description: "Define technical requirements and specifications for the paper"
category: "setup"
version: "1.0"

entry-points:
  primary: "/paper.requirements"
  alternates:
    - "set requirements"
    - "define requirements"

routing:
  primary-agent: "paper-architect"
  workflow: "initialization"
  load-order:
    - "open-agents/INSTRUCTIONS.md"
    - "open-agents/agents/paper_architect.md"

inputs:
  format:
    type: "choice"
    options:
      - "journal-article"
      - "conference-paper"
      - "thesis"
      - "technical-report"
      - "other"
    description: "Publication format"
  
  length:
    type: "text"
    description: "Target length (words or pages)"
  
  constraints:
    type: "text"
    description: "Any specific constraints or requirements"

outputs:
  files:
    - "planning/0000-Project-Overview/requirements.md"
  memory:
    - ".copilot/memory/working-reference.md"

consent-required: false
tools-used: []

behavioral-rules:
  - "Ask about publication venue if not specified"
  - "Clarify formatting requirements"
  - "Identify any hard constraints"

success-criteria:
  - "Requirements clearly documented"
  - "Constraints identified"
  - "Working reference updated"
