#!/usr/bin/env bash
set -euo pipefail

# extract-evidence.sh
# Batch PDF evidence extraction using pdftotext + grep with context
# Usage:
#   ./extract-evidence.sh <pdf_dir> <output_md> [regex_terms...]
# Example:
#   ./extract-evidence.sh ./open-agents/source/reference-materials \
#     ./open-agents/output-refined/research/COMPREHENSIVE_EVIDENCE_EXTRACTION.md \
#     "temporal" "melanopsin|480nm" "von\ Kries|adaptation" "geodesic|manifold"
#
# Notes:
# - Requires `pdftotext` to be installed (poppler-utils)
# - Context flags are set to -A 10 -B 3 by default
# - Produces a simple Markdown report with file and matched contexts

PDF_DIR=${1:-}
OUT_MD=${2:-}
shift 2 || true
TERMS=("$@")

if [[ -z "${PDF_DIR}" || -z "${OUT_MD}" ]]; then
  echo "Usage: $0 <pdf_dir> <output_md> [regex_terms...]" >&2
  exit 1
fi

if [[ ! -d "${PDF_DIR}" ]]; then
  echo "Error: PDF directory not found: ${PDF_DIR}" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_MD}")"

# Header
{
  echo "# Comprehensive Evidence Extraction"
  echo
  echo "Date: $(date -Iseconds)"
  echo "Source Directory: ${PDF_DIR}"
  echo
  echo "---"
} > "${OUT_MD}"

# Iterate PDFs
found_any=false
for pdf in "${PDF_DIR}"/*.pdf; do
  [[ -e "$pdf" ]] || continue
  found_any=true
  fname=$(basename "$pdf")
  echo "\n## Source: ${fname}\n" >> "${OUT_MD}"
  if [[ ${#TERMS[@]} -eq 0 ]]; then
    echo "(No search terms provided; dumping first 20 lines of text as preview)" >> "${OUT_MD}"
    pdftotext "$pdf" - 2>/dev/null | head -n 20 | sed 's/^/    /' >> "${OUT_MD}"
    continue
  fi
  for term in "${TERMS[@]}"; do
    echo "\n### Term: ${term}\n" >> "${OUT_MD}"
    # Extract with context
    pdftotext "$pdf" - 2>/dev/null | grep -E -A 10 -B 3 "$term" | sed 's/^/    /' >> "${OUT_MD}" || {
      echo "    (No matches)" >> "${OUT_MD}"
    }
  done
done

if [[ "${found_any}" = false ]]; then
  echo "\n(No PDFs found in directory)" >> "${OUT_MD}"
fi

# Footer
{
  echo "\n---\n"
  echo "Generated by open-agents/tools/extract-evidence.sh"
} >> "${OUT_MD}"

echo "Evidence extraction complete: ${OUT_MD}"